// Build the enemy ROSTER registry (generator/roster.mjs) consumed by the
// Advanced AI placement feature: labelled groups + collapsed character roles
// per enemy-capable faction.
//
//   node generator/tools/build-roster.mjs
//
// Input = the committed input/roster-labels.json (written by
// tools/label-roster.mjs, which in turn needs the unpacked mods on disk —
// this tool needs only the JSON, so the registry can be rebuilt anywhere).
// Chain after a mod update: harvest-characters → label-roster → build-roster.
//
// Rules:
//  - Groups: every registry groupSets ref, id "<faction>/<setKey>/<stem>",
//    refs = all same-size twins (the emission picks one at random).
//  - Roles: id "<faction>/<slug(subfaction)>/<slug(label)>". 1.8 catalog rule:
//    in a faction that has ANY cataloged character prefab a role is kept only
//    when at least one of its variants is cataloged, but every GUID-bearing
//    variant of a kept role stays (RHS `_2/_3` cosmetic twins are the point of
//    the random pick). Factions without usable catalogs (SFS ×3, RHS_ION,
//    Ses_NAPA) keep everything. Subfactions the registry excludes by design
//    (UK Reservists) are dropped.
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const src = JSON.parse(readFileSync(join(REPO, "input", "roster-labels.json"), "utf8"));

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const ru = (en, r) => (r && r !== en ? r : undefined);

// --- groups ---------------------------------------------------------------------
const groups = {};
for (const g of src.groups) {
  const id = `${g.faction}/${g.setKey}/${g.stem}`;
  const list = (groups[g.faction] ??= []);
  if (list.some((x) => x.id === id)) throw new Error(`duplicate group id ${id}`);
  const classes = [...new Set(g.variants.flatMap((v) => v.classes))];
  list.push({ id, label: g.label, labelRu: ru(g.label, g.labelRu), set: g.setKey, setLabel: g.setLabel, size: g.size, classes, refs: g.variants.map((v) => v.ref) });
}
for (const list of Object.values(groups)) list.sort((a, b) => a.set.localeCompare(b.set) || b.size - a.size || a.label.localeCompare(b.label));

// --- roles ----------------------------------------------------------------------
// Catalog coverage is judged per SUBFACTION: an uncataloged role inside a
// catalog-covered subfaction was delisted on purpose (vanilla US Engineer, USSR
// GateKeeper), while subfactions the catalogs never list at all (RHS FORECON,
// MARSOC MultiCam, VKPO 3.0, SSO, Rosgvardia, ION urban) are kept whole — the
// user asked for every subfaction, and their GUIDs are prefab-side (variant tables).
// …and only for the VANILLA factions, whose catalogs BI maintains as the source
// of truth (the 1.8 rule). Mod catalogs are demonstrably incomplete (RHS's USMC
// catalog omits its own Officer/PL/AT roles, CDF's lists 13 of 79 prefabs), so
// mods keep every GUID-bearing role.
const VANILLA = new Set(["US", "USSR", "FIA"]);
const hasCatalog = {};
for (const r of src.roles) if (VANILLA.has(r.faction) && r.variants.some((v) => v.cataloged)) hasCatalog[`${r.faction}|${r.subfaction}`] = true;
const roles = {};
const dropped = [];
for (const r of src.roles) {
  if (/excluded by design/i.test(r.subfaction)) { dropped.push(`${r.faction}:${r.label} (${r.subfaction})`); continue; }
  if (hasCatalog[`${r.faction}|${r.subfaction}`] && !r.variants.some((v) => v.cataloged)) { dropped.push(`${r.faction}:${r.subfaction}:${r.label} (delisted — no cataloged variant)`); continue; }
  const refs = r.variants.map((v) => v.ref).filter(Boolean);
  if (!refs.length) continue;
  const id = `${r.faction}/${slug(r.subfaction)}/${slug(r.label)}`;
  const list = (roles[r.faction] ??= []);
  if (list.some((x) => x.id === id)) throw new Error(`duplicate role id ${id}`);
  list.push({ id, label: r.label, labelRu: ru(r.label, r.labelRu), subfaction: r.subfaction, set: r.setKey ?? null, refs });
}
for (const list of Object.values(roles)) list.sort((a, b) => a.subfaction.localeCompare(b.subfaction) || a.label.localeCompare(b.label));

// --- emit -----------------------------------------------------------------------
const lit = (o) => JSON.stringify(o).replace(/"([A-Za-z_][A-Za-z0-9_]*)":/g, "$1: ").replace(/,(?=[a-zA-Z_])/g, ", ").replace(/,"/g, ', "');
const emitMap = (name, map) => `export const ${name} = {\n${Object.entries(map).map(([f, list]) => `  ${f}: [\n${list.map((e) => `    ${lit(e)},`).join("\n")}\n  ],`).join("\n")}\n};\n`;
const out = `// AUTO-GENERATED by tools/build-roster.mjs — do not hand-edit.
// Enemy roster for Advanced AI placement: labelled AI groups (every registry
// groupSets ref, twins collapsed) and character ROLES (variant prefabs
// collapsed per subfaction; the emission picks one ref at random per element).
// Source: input/roster-labels.json (tools/label-roster.mjs). labelRu omitted
// when identical to label. Role ids: "<faction>/<subfaction-slug>/<label-slug>";
// group ids: "<faction>/<setKey>/<stem>".
// Regenerate: node generator/tools/build-roster.mjs

${emitMap("ENEMY_GROUPS", groups)}
${emitMap("ENEMY_ROLES", roles)}`;
writeFileSync(join(REPO, "generator", "roster.mjs"), out);
const cnt = (m) => Object.entries(m).map(([f, l]) => `${f} ${l.length}`).join(", ");
console.error(`groups: ${cnt(groups)}`);
console.error(`roles: ${cnt(roles)}`);
console.error(`dropped roles (${dropped.length}): ${dropped.join("; ")}`);
console.error("wrote generator/roster.mjs");
