"use client";

// Arsenal Builder: two-pane modal editing mission.arsenal (the arsenal-crate
// contents). Left = browse the vanilla ARSENAL_POOL (search + faction /
// category / type filters, checkbox add/remove, per-category select-all);
// right = current contents in stored order (category-sorted = in-game order)
// with remove / reset-to-default. Live-commit like every other control — each
// change calls onChange immediately and autosave persists it.
//
// Item names are the harvested in-game names (nameRu when the UI is Russian).
// Mod-faction baked refs aren't in the vanilla pool — they show a humanized
// prefab basename and can be removed but not re-added (mod pool is v2).
//
// Thumbnails: /icons/items/<prefab-basename>.png with a glyph placeholder —
// the images are generated by an engine-side workaround and dropped into
// web/public/icons/items/ later; missing files just keep the glyph.
import { memo, useCallback, useEffect, useMemo, useState } from "react";
import { ARSENAL_POOL, MOD_ARSENAL_POOLS, CORE_ARSENAL_POOL, FACTIONS } from "mission-gen";
import { arsenalPoolByRef, defaultArsenal, sortArsenal } from "@/lib/mission";
import { useLang, useT } from "@/lib/i18n";
import { GhostButton, SectionLabel, SelectInput, TextInput, XButton } from "@/components/ui";

type PoolEntry = (typeof ARSENAL_POOL)[number];

const prefabBasename = (ref: string) => ref.split("/").pop()!.replace(/\.et$/, "");
const humanizeRef = (ref: string) => prefabBasename(ref).replace(/_/g, " ").replace(/\s+/g, " ").trim();
/** "VEST_AND_WAIST" -> "Vest and waist" */
const typeLabel = (t: string) => t.charAt(0) + t.slice(1).toLowerCase().replace(/_/g, " ");

// Dropdown options derive from the ACTIVE pool (vanilla + enabled mods'
// pools), never a hardcoded list — see the useMemos in the component.

/** Enlarged hover preview at the thumbnails' native resolution — upscaling
 * reads blurry at the source res (user-tuned 2026-08-12). */
const PREVIEW_W = 160;
const PREVIEW_H = 120;
type ThumbPreview = { refStr: string; x: number; y: number };
type OnThumbHover = (p: ThumbPreview | null) => void;

/** 40x30 item thumbnail with glyph placeholder (crate glyph) underneath.
 * onHover feeds the modal's shared enlarged-preview tooltip (no delay). */
function ItemThumb({ refStr, onHover }: { refStr: string; onHover?: OnThumbHover }) {
  return (
    <span
      className="relative shrink-0 rounded-[4px] overflow-hidden bg-[#0d0f11] flex items-center justify-center"
      style={{ width: 40, height: 30 }}
      onMouseEnter={(e) => {
        if (!onHover || !window.matchMedia("(hover: hover)").matches) return;
        const r = e.currentTarget.getBoundingClientRect();
        // right of the thumb; flip left when it would clip the viewport
        const x = r.right + 10 + PREVIEW_W > window.innerWidth ? r.left - PREVIEW_W - 10 : r.right + 10;
        const y = Math.max(8, Math.min(window.innerHeight - PREVIEW_H - 8, r.top + r.height / 2 - PREVIEW_H / 2));
        onHover({ refStr, x, y });
      }}
      onMouseLeave={() => onHover?.(null)}
    >
      <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="#3a4147" strokeWidth="1.3" style={{ position: "absolute" }} aria-hidden>
        <path d="M2.5 5.5 8 3l5.5 2.5v5L8 13l-5.5-2.5v-5Z" />
        <path d="M2.5 5.5 8 8l5.5-2.5M8 8v5" />
      </svg>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`/icons/items/${prefabBasename(refStr)}.png`}
        alt=""
        className="absolute inset-0 w-full h-full object-cover"
        loading="lazy"
        onError={(e) => {
          e.currentTarget.style.display = "none";
        }}
      />
    </span>
  );
}

const BrowseRow = memo(function BrowseRow({
  entry,
  name,
  checked,
  onToggle,
  onThumbHover,
}: {
  entry: PoolEntry;
  name: string;
  checked: boolean;
  onToggle: (ref: string) => void;
  onThumbHover: OnThumbHover;
}) {
  return (
    <label
      className={`flex items-center gap-2 rounded-[4px] pl-2 pr-1 py-[3px] cursor-pointer transition-colors ${
        checked ? "bg-[#2e3439]" : "bg-[#14181a] hover:bg-[#1a1f22]"
      }`}
    >
      <input
        type="checkbox"
        checked={checked}
        onChange={() => onToggle(entry.ref)}
        className="shrink-0 size-[14px] accent-[#f4db50]"
      />
      <ItemThumb refStr={entry.ref} onHover={onThumbHover} />
      <span className="flex-1 min-w-0 truncate text-[12px] text-white/80" title={name}>
        {name}
      </span>
      <span className="shrink-0 text-[10px] text-white/35 px-1">{typeLabel(entry.type)}</span>
      {entry.factions.map((f) => (
        <span key={f} className="shrink-0 text-[10px] text-white/50 bg-[#0d0f11] rounded-[3px] px-[5px] py-[1px]">
          {f}
        </span>
      ))}
    </label>
  );
});

export default function ArsenalBuilderModal({
  faction,
  subfaction,
  mods,
  arsenal,
  onChange,
  onClose,
}: {
  faction: string;
  subfaction: string;
  /** Enabled content mods (mission.mods) — gates which mod pools are offered */
  mods: string[];
  arsenal: string[];
  onChange: (refs: string[]) => void;
  onClose: () => void;
}) {
  const t = useT();
  const lang = useLang();
  const itemName = (e: PoolEntry) => (lang === "ru" && e.nameRu ? e.nameRu : e.name);

  // Active browse pool: vanilla + core-addon items (always, no gating) +
  // enabled mods' pools (mod categories normalize onto the vanilla set at
  // harvest, so grouping stays uniform).
  // Mod pools list shared vanilla prefabs alongside their own (RHS lists the
  // vanilla PM, UK the ALICE packs…) — merge by ref so the same item shows
  // ONE row with all its faction chips; first occurrence (vanilla) wins the
  // name/category.
  const pool = useMemo(() => {
    const merged = new Map<string, PoolEntry>();
    for (const e of [...ARSENAL_POOL, ...CORE_ARSENAL_POOL, ...mods.flatMap((id) => MOD_ARSENAL_POOLS[id] ?? [])]) {
      const prev = merged.get(e.ref);
      if (!prev) merged.set(e.ref, e);
      else if (e.factions.some((f) => !prev.factions.includes(f)))
        merged.set(e.ref, { ...prev, factions: [...new Set([...prev.factions, ...e.factions])] });
    }
    return [...merged.values()];
  }, [mods]);
  const poolFactions = useMemo(() => [...new Set(pool.flatMap((i) => i.factions))], [pool]);
  const poolCategories = useMemo(() => [...new Set(pool.map((i) => i.category))], [pool]);
  const poolTypes = useMemo(() => [...new Set(pool.map((i) => i.type))].sort(), [pool]);

  // Playable faction pre-selected; alias factions resolve to their base key
  // (SFS_US -> US); factions without a pool (RHS...) -> All factions.
  const effKey = FACTIONS[faction]?.aliasOf ?? faction;
  const [fFaction, setFFaction] = useState<string>(() => {
    const initial = [...new Set([...ARSENAL_POOL, ...CORE_ARSENAL_POOL, ...mods.flatMap((id) => MOD_ARSENAL_POOLS[id] ?? [])].flatMap((i) => i.factions))];
    return initial.includes(effKey) ? effKey : "all";
  });
  const [fCat, setFCat] = useState<string>("all");
  const [fType, setFType] = useState<string>("all");
  const [search, setSearch] = useState("");
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());
  // Shared enlarged-thumbnail tooltip (instant, follows the hovered thumb)
  const [preview, setPreview] = useState<ThumbPreview | null>(null);
  const onThumbHover = useCallback((p: ThumbPreview | null) => setPreview(p), []);
  const clearPreview = useCallback(() => setPreview(null), []);

  // Esc closes without disturbing the page-level handler's other duties
  // (stopPropagation keeps it from also cancelling placement modes)
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== "Escape") return;
      e.stopPropagation();
      onClose();
    };
    window.addEventListener("keydown", onKey, { capture: true });
    return () => window.removeEventListener("keydown", onKey, { capture: true });
  }, [onClose]);

  const selected = useMemo(() => new Set(arsenal), [arsenal]);

  const filtered = useMemo(() => {
    const terms = search.toLowerCase().split(/\s+/).filter(Boolean);
    return pool.filter((e) => {
      if (fFaction !== "all" && !e.factions.includes(fFaction)) return false;
      if (fCat !== "all" && e.category !== fCat) return false;
      if (fType !== "all" && e.type !== fType) return false;
      if (terms.length) {
        const hay = `${e.name} ${e.nameRu ?? ""} ${e.ref} ${e.type}`.toLowerCase();
        if (!terms.every((term) => hay.includes(term))) return false;
      }
      return true;
    });
  }, [pool, search, fFaction, fCat, fType]);

  const grouped = useMemo(() => {
    const g = new Map<string, PoolEntry[]>();
    for (const cat of poolCategories) g.set(cat, []);
    for (const e of filtered) g.get(e.category)!.push(e);
    return [...g.entries()].filter(([, items]) => items.length > 0);
  }, [filtered, poolCategories]);

  const toggle = (ref: string) => {
    if (selected.has(ref)) {
      if (arsenal.length === 1) return; // min 1 — an empty conf override would leave the base placeholder member
      onChange(arsenal.filter((r) => r !== ref));
    } else {
      onChange(sortArsenal([...arsenal, ref]));
    }
  };

  const selectAll = (items: PoolEntry[]) => {
    const add = items.filter((e) => !selected.has(e.ref)).map((e) => e.ref);
    if (add.length) onChange(sortArsenal([...arsenal, ...add]));
  };

  const filtersActive = fFaction !== "all" || fCat !== "all" || fType !== "all" || search !== "";

  return (
    <div
      className="fixed inset-0 z-[3000] bg-black/60 flex items-start justify-center p-4 pt-[6vh]"
      onClick={onClose}
    >
      <div
        className="bg-[#202427] rounded-[12px] p-4 flex flex-col gap-3 w-full max-w-[1100px] h-[85dvh] shadow-[0px_16px_32px_0px_rgba(0,0,0,0.4)] animate-[mbFadeSlide_0.25s_ease]"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center gap-2">
          <h2 className="font-slab text-[16px] font-medium text-white flex-1">{t("Arsenal Builder")}</h2>
          <XButton ariaLabel={t("Dismiss")} onClick={onClose} />
        </div>

        <div className="flex flex-col sm:flex-row gap-3 min-h-0 flex-1">
          {/* Left: browse the vanilla pool */}
          <div className="flex-1 min-w-0 flex flex-col gap-2 min-h-0">
            <TextInput
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder={t("Search items…")}
              className="!h-[36px] text-[12px]"
            />
            <div className="flex gap-2">
              <SelectInput value={fFaction} onChange={(e) => setFFaction(e.target.value)} className="!h-[36px] flex-1 min-w-0 text-[12px]">
                <option value="all">{t("All factions")}</option>
                {poolFactions.map((f) => (
                  <option key={f} value={f}>
                    {f}
                  </option>
                ))}
              </SelectInput>
              <SelectInput value={fCat} onChange={(e) => setFCat(e.target.value)} className="!h-[36px] flex-1 min-w-0 text-[12px]">
                <option value="all">{t("All categories")}</option>
                {poolCategories.map((c) => (
                  <option key={c} value={c}>
                    {t(c)}
                  </option>
                ))}
              </SelectInput>
              <SelectInput value={fType} onChange={(e) => setFType(e.target.value)} className="!h-[36px] flex-1 min-w-0 text-[12px]">
                <option value="all">{t("All types")}</option>
                {poolTypes.map((ty) => (
                  <option key={ty} value={ty}>
                    {typeLabel(ty)}
                  </option>
                ))}
              </SelectInput>
              {filtersActive && (
                <GhostButton
                  small
                  onClick={() => {
                    setFFaction("all");
                    setFCat("all");
                    setFType("all");
                    setSearch("");
                  }}
                  className="shrink-0"
                >
                  {t("Clear filters")}
                </GhostButton>
              )}
            </div>

            <div className="flex-1 overflow-y-auto ts-thin-scrollbar pr-1 flex flex-col gap-1" onScroll={clearPreview}>
              {grouped.length === 0 && (
                <span className="text-[12px] text-white/40 py-4 text-center">{t("No items match the filters.")}</span>
              )}
              {grouped.map(([cat, items]) => {
                const isCollapsed = collapsed.has(cat);
                return (
                  <div key={cat} className="flex flex-col gap-1">
                    <div className="flex items-center gap-2 pt-1">
                      <button
                        type="button"
                        onClick={() =>
                          setCollapsed((prev) => {
                            const next = new Set(prev);
                            if (next.has(cat)) next.delete(cat);
                            else next.add(cat);
                            return next;
                          })
                        }
                        className="flex items-center gap-[6px] text-[12px] text-white/60 hover:text-white transition-colors"
                      >
                        <span className={`inline-block transition-transform text-[9px] ${isCollapsed ? "" : "rotate-90"}`}>▶</span>
                        {t(cat)}
                        <span className="text-white/35">({items.length})</span>
                      </button>
                      <span className="flex-1" />
                      <button
                        type="button"
                        onClick={() => selectAll(items)}
                        className="text-[11px] text-[#f4db50]/70 hover:text-[#f4db50] transition-colors"
                      >
                        {t("Select all")}
                      </button>
                    </div>
                    {!isCollapsed &&
                      items.map((e) => (
                        <BrowseRow
                          key={e.ref}
                          entry={e}
                          name={itemName(e)}
                          checked={selected.has(e.ref)}
                          onToggle={toggle}
                          onThumbHover={onThumbHover}
                        />
                      ))}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Right: current arsenal contents (stored order = in-game order) */}
          <div className="sm:w-[340px] shrink-0 flex flex-col gap-2 min-h-0 max-h-[38%] sm:max-h-none border-t sm:border-t-0 sm:border-l border-[#2e3439] pt-2 sm:pt-0 sm:pl-3">
            <div className="flex items-center gap-2">
              <SectionLabel>
                {t("Arsenal contents")}{" "}
                <span className="text-white/35">{t("· {n} items").replace("{n}", String(arsenal.length))}</span>
              </SectionLabel>
              <span className="flex-1" />
              <GhostButton small onClick={() => onChange(sortArsenal(defaultArsenal(faction, subfaction)))}>
                {t("Reset")}
              </GhostButton>
            </div>
            <div className="flex-1 overflow-y-auto ts-thin-scrollbar pr-1 flex flex-col gap-1" onScroll={clearPreview}>
              {arsenal.map((ref) => {
                const entry = arsenalPoolByRef.get(ref);
                const last = arsenal.length === 1;
                return (
                  <div key={ref} className="flex items-center gap-2 rounded-[4px] bg-[#14181a] pl-2 pr-1 py-[3px]">
                    <ItemThumb refStr={ref} onHover={onThumbHover} />
                    <span className="flex-1 min-w-0 truncate text-[12px] text-white/80" title={entry ? itemName(entry) : ref}>
                      {entry ? itemName(entry) : humanizeRef(ref)}
                    </span>
                    <span
                      title={last ? t("The arsenal must keep at least one item.") : undefined}
                      className={last ? "opacity-30 pointer-events-none" : ""}
                    >
                      <XButton ariaLabel={t("Remove item")} onClick={() => toggle(ref)} />
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Enlarged-thumbnail tooltip: instant (no transition/delay), fixed so
            the scroll containers can't clip it, pointer-events-none so it can
            never steal the hover and flicker. */}
        {preview && (
          <div
            className="fixed z-[3100] pointer-events-none rounded-[8px] overflow-hidden bg-[#0d0f11] border border-[#2e3439] shadow-[0px_16px_32px_0px_rgba(0,0,0,0.6)]"
            style={{ left: preview.x, top: preview.y, width: PREVIEW_W, height: PREVIEW_H }}
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`/icons/items/${prefabBasename(preview.refStr)}.png`}
              alt=""
              className="w-full h-full object-contain"
              onError={(e) => {
                e.currentTarget.style.display = "none";
              }}
            />
          </div>
        )}
      </div>
    </div>
  );
}
